inherit_from: .rubocop_todo.yml

require: 
    - rubocop-rails
    - rubocop-rspec

AllCops:
    NewCops: enable

Metrics/BlockLength: 
  Exclude: 
    - spec/**/*

Rails/NotNullColumn:
    Exclude:
        - db/migrate/20230607091520_add_jti_to_users.rb

Style/Documentation:
    Enabled: false

RSpec/AnyInstance:
    Enabled: false

Rails/HasAndBelongsToMany:
    Enabled: false

RSpec/InstanceVariable:
    Enabled: false

